// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebProgramlama_Odev.Models;

#nullable disable

namespace WebProgramlama_Odev.Migrations
{
    [DbContext(typeof(AirlineContext))]
    partial class AirlineContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebProgramlama_Odev.Models.AdminModel", b =>
                {
                    b.Property<int>("IdAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAdmin"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdAdmin");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("WebProgramlama_Odev.Models.GuzergahModel", b =>
                {
                    b.Property<int>("UcusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UcusId"), 1L, 1);

                    b.Property<string>("Nereden")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nereye")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.HasKey("UcusId");

                    b.ToTable("Guzergah");
                });

            modelBuilder.Entity("WebProgramlama_Odev.Models.UcusModel", b =>
                {
                    b.Property<int>("PnrNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PnrNo"), 1L, 1);

                    b.Property<int>("UcusId")
                        .HasColumnType("int");

                    b.HasKey("PnrNo");

                    b.HasIndex("UcusId");

                    b.ToTable("Ucus");
                });

            modelBuilder.Entity("WebProgramlama_Odev.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"), 1L, 1);

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("firstname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lastname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("phone")
                        .HasColumnType("bigint");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WebProgramlama_Odev.Models.UserUcus", b =>
                {
                    b.Property<int>("UserUcusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserUcusId"), 1L, 1);

                    b.Property<int>("PnrNo")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserUcusId");

                    b.HasIndex("PnrNo");

                    b.HasIndex("UserId");

                    b.ToTable("UserUcus");
                });

            modelBuilder.Entity("WebProgramlama_Odev.Models.UcusModel", b =>
                {
                    b.HasOne("WebProgramlama_Odev.Models.GuzergahModel", "Guzergah")
                        .WithMany("Ucuss")
                        .HasForeignKey("UcusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guzergah");
                });

            modelBuilder.Entity("WebProgramlama_Odev.Models.UserUcus", b =>
                {
                    b.HasOne("WebProgramlama_Odev.Models.UcusModel", "Ucus")
                        .WithMany("UserUcuss")
                        .HasForeignKey("PnrNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebProgramlama_Odev.Models.User", "User")
                        .WithMany("UserUcuss")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ucus");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebProgramlama_Odev.Models.GuzergahModel", b =>
                {
                    b.Navigation("Ucuss");
                });

            modelBuilder.Entity("WebProgramlama_Odev.Models.UcusModel", b =>
                {
                    b.Navigation("UserUcuss");
                });

            modelBuilder.Entity("WebProgramlama_Odev.Models.User", b =>
                {
                    b.Navigation("UserUcuss");
                });
#pragma warning restore 612, 618
        }
    }
}
